.TH "reporter-vz" 1 "October 2015" "OpenVZ"
.nh
.ad l

.SH "NAME"
reporter-vz \- Sends problem report to Virtuozzo technical support\&.

.SH "SYNOPSIS"
reporter-vz [\fBDIR\fP]

.SH "DESCRIPTION"
The tool reads and processes the problem directory \fBDIR\fP\&, then sends the problem report from it to Virtuozzo technical support\&.

If not specified, \fBDIR\fP defaults to the current directory\&.

.SH "SEE ALSO"
virtuozzo_event\&.conf(5), prlctl(8), prlsrvctl(8)

.SH "COPYRIGHT"
Copyright (c) 2015-2015 Parallels IP Holdings GmbH. All rights reserved.
