.TH "virtuozzo_event\&.conf" 5 "October 2015" "OpenVZ"
.nh
.ad l

.SH "NAME"
virtuozzo_event.conf \- The configuration file for libreport\&.

.SH "DESCRIPTION"
This configuration file provides crash event handlers that use \fIprlctl\fR and \fIprlsrvctl\fR for problem reporting\&.

By default\&, this file contains an event handler for qemu and executables from Virtuozzo packages

.SH "SEE ALSO"
report_event\&.conf(5), prlctl(8), prlsrvctl(8) 

.SH "COPYRIGHT"
Copyright (c) 2015-2015 Parallels IP Holdings GmbH. All rights reserved.
